demos/Demo02/SynergisticLogging.Web/Models/ErrorViewModel.cs
namespace SynergisticLogging.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

demos/Demo02/SynergisticLogging.Web/Controllers/DadJokesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SynergisticLogging.Web.Data;
using SynergisticLogging.Web.External;
using SynergisticLogging.Web.Logging.ActionLogger;

namespace SynergisticLogging.Web.Controllers
{
    [LoggingActionFilter]
    public class DadJokesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDadJokesApiService _dadJokesApiService;
        public DadJokesController(ApplicationDbContext context, IDadJokesApiService dadJokesApiService)
        {
            _context = context;
            _dadJokesApiService = dadJokesApiService;
        }

        // GET: DadJokes
        public async Task<IActionResult> Index()
        {
              return _context.DadJokes != null ? 
                          View(await _context.DadJokes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.DadJokes'  is null.");
        }

        // GET: DadJokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DadJokes == null)
            {
                return NotFound();
            }

            var dadJoke = await _context.DadJokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dadJoke == null)
            {
                return NotFound();
            }

            return View(dadJoke);
        }

        // GET: DadJokes/Create
        public IActionResult Create()
        {
            var joke = new DadJoke();
            return View();
        }

        public async Task<IActionResult> GetRandom()
        {
            var joke = await _dadJokesApiService.GetRandom();
            _context.Add(joke);
            _context.SaveChanges();

            return _context.DadJokes != null ?
                          View("Index",await _context.DadJokes.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.DadJokes'  is null.");
        }
        // POST: DadJokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Setup,Punchline")] DadJoke dadJoke)
        {
            if (ModelState.IsValid)
            {
                dadJoke.CreatedDate = DateTime.Now;
                _context.Add(dadJoke);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dadJoke);
        }

        // GET: DadJokes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DadJokes == null)
            {
                return NotFound();
            }

            var dadJoke = await _context.DadJokes.FindAsync(id);
            if (dadJoke == null)
            {
                return NotFound();
            }
            return View(dadJoke);
        }

        // POST: DadJokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Setup,Punchline,CreatedDate")] DadJoke dadJoke)
        {
            if (id != dadJoke.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dadJoke);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DadJokeExists(dadJoke.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dadJoke);
        }

        // GET: DadJokes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DadJokes == null)
            {
                return NotFound();
            }

            var dadJoke = await _context.DadJokes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dadJoke == null)
            {
                return NotFound();
            }

            return View(dadJoke);
        }

        // POST: DadJokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DadJokes == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DadJokes'  is null.");
            }
            var dadJoke = await _context.DadJokes.FindAsync(id);
            if (dadJoke != null)
            {
                _context.DadJokes.Remove(dadJoke);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DadJokeExists(int id)
        {
          return (_context.DadJokes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

demos/Demo02/SynergisticLogging.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SynergisticLogging.Web.Models;
using System.Diagnostics;
using SynergisticLogging.Web.Logging.ActionLogger;

namespace SynergisticLogging.Web.Controllers
{
    [LoggingActionFilter]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

demos/Demo02/SynergisticLogging.Web/Views/DadJokes/Create.cshtml
@model SynergisticLogging.Web.Data.DadJoke

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DadJoke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Setup" class="control-label"></label>
                <input asp-for="Setup" class="form-control" />
                <span asp-validation-for="Setup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Punchline" class="control-label"></label>
                <input asp-for="Punchline" class="form-control" />
                <span asp-validation-for="Punchline" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

demos/Demo02/SynergisticLogging.Web/Views/DadJokes/Delete.cshtml
@model SynergisticLogging.Web.Data.DadJoke

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DadJoke</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Punchline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Punchline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

demos/Demo02/SynergisticLogging.Web/Views/DadJokes/Details.cshtml
@model SynergisticLogging.Web.Data.DadJoke

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DadJoke</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Setup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Setup)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Punchline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Punchline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

demos/Demo02/SynergisticLogging.Web/Views/DadJokes/Edit.cshtml
@model SynergisticLogging.Web.Data.DadJoke

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DadJoke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Setup" class="control-label"></label>
                <input asp-for="Setup" class="form-control" />
                <span asp-validation-for="Setup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Punchline" class="control-label"></label>
                <input asp-for="Punchline" class="form-control" />
                <span asp-validation-for="Punchline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

demos/Demo02/SynergisticLogging.Web/Views/DadJokes/Index.cshtml
@model IEnumerable<SynergisticLogging.Web.Data.DadJoke>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>&nbsp;|&nbsp;<a asp-action="GetRandom">Get Random</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Setup)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Punchline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Setup)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Punchline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

demos/Demo02/SynergisticLogging.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

demos/Demo02/SynergisticLogging.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SynergisticLogging.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SynergisticLogging.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SynergisticLogging.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DadJokes" asp-action="Index">Dad Jokes</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SynergisticLogging.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>